### ISSUE TITLE
Feature Request: Emby plugin

### ISSUE THREAD

**Issue by tatoomana** [ddurdle/GDrive-for-KODI#91] opened 2016-09-06 00:40 UTC
Hi Dylan,

I started a [topic](http://emby.media/community/index.php?/topic/33488-google-drive-as-source/) for the development of a plugin for a Google Drive integration in Emby Server.

I wish to know what you think about that and maybe in the hope you can do it. :)

**Comment by ddurdle** [comment] 2016-09-06 14:24
How would it be different then the Google Drive sync included with Emby?

**Comment by tatoomana** [comment] 2016-09-06 23:51
The google drive sync included with Emby is only a backup for video
transcoded by Emby.

**Comment by qazero** [comment] 2017-04-08 00:52
Any update regarding this so we can stream directly from google drive using Emby's webui?

**Comment by ddurdle** [comment] 2017-07-30 15:36
duplicate of https://github.com/ddurdle/GDrive-for-KODI/issues/116

**Comment by ddurdle** [comment] 2018-05-03 01:56
implemented as part of Python-GoogleDrive-VideoStream

**Closed by ddurdle** 2018-05-03 01:56 UTC
