### ISSUE TITLE
Folder Creation When Saving STRM - additional subdirectories and blank folder names

### ISSUE THREAD

**Issue by negroISO** [ddurdle/GDrive-for-KODI#105] opened 2016-11-26 15:28 UTC
Kodi 16.1 and Kodi 17Beta5

When Saving STRM from Movie/Television root folder, G-Drive now creates the following example for every tv series:

X:\Television Name\TV
X:\Television Name\movies
X:\Television Name\music
X:\Television Name\other-video
X:\Television Name\pictures
X:\Television Name\Season01\
X:\Television Name\Season02\

Also, for some strange reason when I do save STRM on a "Television" directory, it creates a blank folder, not recognized by Windows/NTFS I presume, and when you click on it, it just repeats the contents of the main folder. Then it makes it impossible to delete without command line interjection.

I'm not sure if there's a setting I missed or what, but even after telling it to export strm for a single folder, the "STRM" counter keeps going up, like it's searching my entire G-Drive for content.

Let me know if you need anymore info.

Kodi 16.1 - Windows 10 x64 Pro - latest G-Drive as of 11/26/16

**Comment by Tackyou** [comment] 2016-12-12 04:59
I have the same problem. Everything gets added double now. Why did it suddenly start making these tv and movie subfolders that just mess everything up? Any ETA on when this will be fixed?

**Comment by negroISO** [comment] 2016-12-12 18:29
I found that I just installed an older version. The current 0.8.35 does it, but the 0.8.05 doesn't do it. However, if you have Kodi auto-update plugins then you get the 0.8.35. I can say that it also effects Kodi 16 as well, so I'm leaning to it's an issue with the plugin and not Kodi.

It appears like it's trying to do some Auto-STRM generation. I even reset the plugin back to defaults (which fixed my next chapter button issue), but not the folders within folders within folders thing.

**Comment by ddurdle** [comment] 2016-12-12 20:06
I'm investigating.  I've been able to reproduce in gdrive-testing 0.8.35 but not gdrive 0.8.35.  Which are you using?  I haven't had time to check the debug, but the playback of a particular file in one works but not in the other.

**Comment by Tackyou** [comment] 2016-12-12 20:06
He added it in 0.8.26, see the change to this file https://github.com/ddurdle/GDrive-for-KODI/commit/37e73df853f988da4ee756ff5bed69a959ae9315

**Comment by negroISO** [comment] 2016-12-12 20:16
Yup, I created my "Movies" strm with 0.8.05 but then Kodi Auto-updated to 0.8.35. I went to save "Television" strm and now multiple folders inside folders exist. I have both gdrive-testing and gdrive installed, however I ran the save strm from the regular and not the testing. I will downgrade back to 0.8.05 for my main one.

**Comment by Tackyou** [comment] 2016-12-22 07:08
@ddurdle Hm, weird that you don't have it with 0.8.35. Did you install it from the repo? In Kodi 17 beta there's a version choice menu coming up when you install the plugin from repo asking 0.8.05 or 0.8.35, in Kodi 16 there is no choice available and it will install 0.8.35. With 0.8.35 from the repo the issue is present, with 0.8.05 it's not.

Working: http://dmdsoftware.net/repository.ddurdle/plugin.video.gdrive-0.8.05.zip
Broken: http://dmdsoftware.net/repository.ddurdle/plugin.video.gdrive-0.8.35.zip

**Comment by ddurdle** [comment] 2016-12-22 13:19
I will investigate

**Comment by negroISO** [comment] 2016-12-22 18:55
I just removed the add-on and the repo, then re-added the repo and
installed 0.8.05 and told Kodi/LibreElec not to auto-update plugins. It
looks like the plugin is trying to auto create STRM no matter if you have
that option turned on or off.

**Comment by alvins82** [comment] 2017-01-03 11:11
Confirmed this is an issue on 0.8.35 - both testing gdrive-testing and gdrive. Tested 0.8.05 and works fine as above.

**Comment by MONKiCODE** [comment] 2017-01-04 10:43
Yup I got the same issue. And each movie file has two STRM files. One straight under each movie folder and an additional one under the extra subfolder called "movies."
Any fixes coming?

**Comment by ddurdle** [comment] 2017-01-05 20:37
In the testing version.  Once I receive ok issue is resolved there, I will push out to non-testing version

**Comment by robinmalik** [comment] 2017-01-12 13:18
Kodi 16.1 | Windows 10 x64 Pro | GDrive 0.8.37 = No issue for me.

**Comment by Tackyou** [comment] 2017-01-13 15:16
Kodi 17.0-BETA7 | Apple TV 4 | GDrive 0.8.37 = All fine no duplicates.
Thank you for the fix

**Comment by negroISO** [comment] 2017-03-08 21:12
Is 0.8.37 being pushed to the regular or is Testing still in testing?

**Comment by ddurdle** [comment] 2017-03-08 22:40
will push out to regular

**Comment by negroISO** [comment] 2017-03-09 15:19
Thank you so much!

**Closed** 2017-08-08 01:51 UTC
Labels: bug, in-testing
